//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.FingerPrintSync.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_READER
    {
        public int nReaderIdn { get; set; }
        public string sName { get; set; }
        public int nType { get; set; }
        public int nDeptIdn { get; set; }
        public string sIP { get; set; }
        public string sMacAddress { get; set; }
        public int nConnType { get; set; }
        public string sDescription { get; set; }
        public int IsEmailNotifyEnable{ get; set; }
        public int IsLogSyncEnable { get; set; }
    }
}
