//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.FingerPrintSync.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public string ipAddress { get; set; }
        public DateTime logTime { get; set; }
        public string userId { get; set; }
        public string punchType { get; set; }
        public string deviceId { get; set; }
        public DateTime updatedAt { get; set; }
        public bool IsSynced { get; set; }
        public bool IsInvalid { get; set; }
    }
}
