//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.FingerPrintSync.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomIP
    {
        public short id { get; set; }
        public string ipAddress { get; set; }
        public string roomNumber { get; set; }
        public string description { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
