//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.FingerPrintSync.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public int nUserIdn { get; set; }
        public string sUserName { get; set; }
        public int nDepartmentIdn { get; set; }
        public string sTelNumber { get; set; }
        public string sEmail { get; set; }
        public string sUserID { get; set; }
        public string sPassword { get; set; }
        public byte[] bPassword2 { get; set; }
        public int nStartDate { get; set; }
        public int nEndDate { get; set; }
        public int nAdminLevel { get; set; }
        public int nAuthMode { get; set; }
        public int nAuthLimitCount { get; set; }
        public int nTimedAPB { get; set; }
        public int nEncryption { get; set; }
    }
}
